spring:
  datasource:
    mapper-locations: classpath:/mappers/*.xml
    username: api
    jdbc-url: jdbc:mysql://db:3306/shop_api?&serverTimezone=UTC&autoReconnect=true&allowMultiQueries=true&characterEncoding=UTF-8
    driver: com.mysql.cj.jdbc.Driver
    password: hm041400
  main:
    allow-circular-references: true

logging:
    level:
      root: info
